apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort # Added to expose service via NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081 # Optional: specify a port or let Kubernetes assign one
  selector:
    app: guestbook-ui
